### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by aydint420** [R3DHULK/fsociety#2]
doing pip install of the requirements.txt, and i get error metadata-generation-failed

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-e8e3k85x/turtle_ea48579067a54014a24dbf3cc134043b/setup.py", line 40
          except ValueError, ve:
                 ^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

any idea how to fix this?

**Comment by R3DHULK** [comment]
Let me check first

**Comment by R3DHULK** [comment]
I found everything is fine in my case, if you meet with any error further or you tackled any error kindly inform me. Also installing pip packages now have changed, take that note. Running fsociety is not a headache but including tools are.
